apiVersion: v2
name: altar-trader-hub
description: Altar Trader Hub Backend - Crypto Trading Bot
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - trading
  - crypto
  - bot
  - fastapi
  - python
home: https://github.com/your-org/altar-trader-hub-be
sources:
  - https://github.com/your-org/altar-trader-hub-be
maintainers:
  - name: Altar Team
    email: team@altar.com
dependencies:
  - name: postgresql
    version: 12.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.3.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: 19.6.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 6.43.5
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
