apiVersion: v1
kind: Service
metadata:
  name: {{ include "altar-trader-hub.fullname" . }}
  labels:
    {{- include "altar-trader-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "altar-trader-hub.selectorLabels" . | nindent 4 }}
