apiVersion: v1
kind: ServiceMonitor
metadata:
  name: altar-trader-hub-api-monitor
  namespace: altar-trader-hub
  labels:
    app: altar-trader-hub-api
spec:
  selector:
    matchLabels:
      app: altar-trader-hub-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: altar-trader-hub-celery-monitor
  namespace: altar-trader-hub
  labels:
    app: altar-trader-hub-celery-worker
spec:
  selector:
    matchLabels:
      app: altar-trader-hub-celery-worker
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: altar-trader-hub-alerts
  namespace: altar-trader-hub
spec:
  groups:
  - name: altar-trader-hub
    rules:
    - alert: APIDown
      expr: up{job="altar-trader-hub-api"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Altar Trader Hub API is down"
        description: "The API has been down for more than 1 minute"
    
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High error rate detected"
        description: "Error rate is above 10% for 5 minutes"
    
    - alert: HighResponseTime
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High response time detected"
        description: "95th percentile response time is above 1 second"
    
    - alert: CeleryWorkerDown
      expr: up{job="altar-trader-hub-celery"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Celery worker is down"
        description: "A Celery worker has been down for more than 1 minute"
    
    - alert: DatabaseConnectionFailed
      expr: up{job="postgres"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Database connection failed"
        description: "Cannot connect to PostgreSQL database"
    
    - alert: RedisConnectionFailed
      expr: up{job="redis"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Redis connection failed"
        description: "Cannot connect to Redis cache"
