apiVersion: v1
kind: Secret
metadata:
  name: altar-trader-hub-secrets
  namespace: altar-trader-hub
type: Opaque
data:
  SECRET_KEY: <base64-encoded-secret-key>
  POSTGRES_PASSWORD: <base64-encoded-postgres-password>
  REDIS_PASSWORD: <base64-encoded-redis-password>
  SMTP_PASSWORD: <base64-encoded-smtp-password>
  TELEGRAM_BOT_TOKEN: <base64-encoded-telegram-token>
